version: '2'
services:


  #
  # Data mounted volume
  #
  data:
    image: tianon/true
    container_name: fw-data
    volumes:
      - './data:/data'


  #
  # LOAD BALANCER (Nginx)
  # Host: filewatcher.local
  #
  load-balancer:
    image: fw-load-balancer
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    container_name: fw-load-balancer
    networks:
      - filewatcher
    ports:
      - "80:80"
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: filewatcher.local

  #
  # MASTER NODE
  #
  server-node:
    image: fw-server-node
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server.dev  # Can be changed for prod
    container_name: fw-server-node
    networks:
      - filewatcher
    ports:
      - "8000:80"
    volumes:
      - './server:/go/src/server'
    environment:
      PORT: 80


  #
  # WATCHER NODE 
  #
  watcher-node:
    image: fw-watcher-node
    build:
      context: .
      dockerfile: ./docker/Dockerfile.watcher.dev # Can be changed for prod
    networks:
      - filewatcher
    volumes:
      - './watcher:/go/src/watcher'
    depends_on:
      - data
      - server-node
    links:
      - data
    environment:
      LB_HOST: load-balancer
      LB_PORT: 80
      DIR_PATH: /data


networks:
  filewatcher:
    driver: bridge