FROM golang:latest

COPY ./watcher /go/src/watcher
WORKDIR /go/src/watcher

RUN mkdir /trash
RUN mkdir /logs

RUN go get -v ./...
RUN go install -v ./...

RUN go get github.com/pln0w/fresh
COPY ./runner.conf /runner.conf
CMD fresh -c /runner.conf

EXPOSE 4000
