FROM golang:alpine AS builder

COPY ./server /go/src/server
WORKDIR /go/src/server

RUN mkdir /logs

RUN apk add --no-cache git

RUN go get -v ./...
RUN go install -v ./...

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o server.

FROM alpine:latest

RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/server /aserverpp

ENTRYPOINT ./server

LABEL Name=filewatcher Version=0.0.1

EXPOSE 3000