FROM golang:alpine AS builder

COPY ./watcher /go/src/watcher
WORKDIR /go/src/watcher

RUN mkdir /trash
RUN mkdir /logs

RUN apk add --no-cache git

RUN go get -v ./...
RUN go install -v ./...

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o watcher.

FROM alpine:latest

RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/watcher /watcher

ENTRYPOINT ./watcher

LABEL Name=filewatcher Version=0.0.1

EXPOSE 4000