FROM golang:latest

COPY ./master /go/src/app
WORKDIR /go/src/app
RUN mkdir /go/src/app/logs

RUN go get ./...
RUN go install ./...
RUN go build -o main

CMD go get github.com/pilu/fresh && cd /go/src/app && fresh

EXPOSE 3000
